openapi: 3.0.3
info:
  title: Retell Booking Service
  version: 1.0.0
paths:
  /healthz:
    get:
      summary: Liveness probe
      responses:
        '200':
          description: OK
  /retell/public/check_availability:
    post:
      summary: HotelRunner availability proxy (public)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckAvailability'
      responses:
        '200':
          description: Availability response
          content:
            application/json:
              schema:
                type: object
        '4XX':
          description: Validation error
        '5XX':
          description: Upstream error
  /retell/tool/compose_offer:
    post:
      summary: Compose an offer (FX & policy)
      parameters:
        - name: X-Tool-Secret
          in: header
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComposeOffer'
      responses:
        '200':
          description: Offer
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    CheckAvailability:
      type: object
      required: [check_in, check_out, adults, children]
      properties:
        check_in: { type: string, pattern: "^\d{4}-\d{2}-\d{2}$" }
        check_out: { type: string, pattern: "^\d{4}-\d{2}-\d{2}$" }
        adults: { type: integer, minimum: 1, maximum: 8 }
        children: { type: integer, minimum: 0, maximum: 8 }
        currency: { type: string, minLength: 3, maxLength: 3 }
    ComposeOffer:
      type: object
      required: [availability_result]
      properties:
        availability_result: { type: object }
        display_currency: { type: string, minLength: 3, maxLength: 3 }
        user_choice: { type: string }
        channel_default: { type: string }
        phone_country: { type: string, minLength: 2, maxLength: 2 }
        ip_country: { type: string, minLength: 2, maxLength: 2 }
