services:
  - type: web
    name: retell-agent-optimized
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    runtime: "node"
    region: frankfurt
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TOOL_SECRET
        sync: false
      - key: HOTELRUNNER_BASE
        value: https://api2.hotelrunner.com
      - key: HOTELRUNNER_AVAILABILITY_PATH
        value: /api/v1/availability/search
      - key: HOTELRUNNER_TOKEN
        sync: false
      - key: HOTELRUNNER_ID
        sync: false
